config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'portfolio#homepage'

  get 'about', to: 'portfolio#about'

  get 'landscapes', to: 'pages#landscapes'

  get 'animals', to: 'pages#animals'

  get 'birds', to: 'pages#birds'

  get 'macros', to: 'pages#macros'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landscapes
    @images = Dir.glob("#{Rails.root}/app/assets/images/landscapes/*.jpg")

  end

  def animals
    @images = Dir.glob("#{Rails.root}/app/assets/images/animals/*.jpg")
  end

  def birds
    @images = Dir.glob("#{Rails.root}/app/assets/images/birds/*.jpg")
  end

  def macros
    @images = Dir.glob("#{Rails.root}/app/assets/images/macros/*.jpg")
  end

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def homepage

  end

  def about

  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class='footer'>
    <small>
      Copyright &copy; 2019 by Katalin B.
    </small>
    <nav>
      <%= link_to 'About', about_path %>
    </nav>
  </footer>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar transparent justify-content-center navbar-fixed-top navbar-expand-sm">
  <%= image_tag("logo.png", size:"30x35", :alt => "owl logo", class: "logo") %>
  <%= link_to "KA's shots", root_path, class:'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to 'Landscape', landscapes_path, class: 'nav-link' %>
      <%= link_to 'Animals', animals_path, class: 'nav-link' %>
      <%= link_to 'Macro', macros_path, class: 'nav-link' %>
      <%= link_to 'Birds', birds_path, class: 'nav-link' %>
    </div>
  </div>
</nav>

 <!-- #pull-right ass a class in a container with, for ex elements of the navbar, pulling them to the right -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioKate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/animals.html.erb

<div class="container">
  <h1 class="display-4">Our friends</h1>

 <div class="animals">
  <div class="row">
    <% @images.each do |image| %>
      <div class="polaroid">
        <div class="rounded">
          <%= image_tag "animals/#{ File.basename(image) }", class: 'img-responsive rounded', style: 'width:100%' %>
        </div>
      </div>
    <% end %>
  </div>
 </div>
</div>

app/views/pages/birds.html.erb

<div class="container">
  <h1 class="display-4">Feathers . . .</h1>

 <div class="birds">
  <div class="row">
    <% @images.each do |image| %>
      <div class="polaroid">
        <div class="rounded">
          <%= image_tag "birds/#{ File.basename(image) }", class: 'img-responsive rounded', style: 'width:100%' %>
        </div>
      </div>
    <% end %>
  </div>
 </div>
</div>

app/views/pages/landscapes.html.erb

<div class="container">
  <h1 class="display-4">Beautiful landscapes from around the world!</h1>

 <div class="landscapes">
  <div class="row">
    <% @images.each do |image| %>
      <div class="polaroid">
        <div class="rounded">
          <%= image_tag "landscapes/#{ File.basename(image) }", class: 'img-responsive rounded', style: 'width:100%' %>
        </div>
      </div>
    <% end %>
  </div>
 </div>
</div>

app/views/pages/macros.html.erb

<div class="container">
  <h1 class="display-4">The amazing micro world!</h1>

  <div class="macros">
    <div class="row">
      <% @images.each do |image| %>
        <div class="polaroid">
          <div class="rounded">
          <%= image_tag "macros/#{ File.basename(image) }", class: 'img-responsive rounded', style: 'width:100%' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/portfolio/about.html.erb
<h1 align='center'>About me and my passion</h1>

app/views/portfolio/homepage.html.erb
<main role='main'>
<div class="container">
  <h1 class='display-4'>The world through my eyes</h1>

  <div class="row">
    <div class="col-xs-6 col-lg-6">
      <div class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-interval="time">
            <%= image_tag 'landscapes/landscape (1)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (2)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (3)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (4)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (5)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (6)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (7)', width:450, height:300 %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-lg-6">
      <div class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-interval="900">
            <%= image_tag 'landscapes/landscape (1)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (2)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (3)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (4)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (5)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (6)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (7)', width:450, height:300 %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class='row'>
    <div class="col-xs-6 col-lg-6">
      <div class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-interval="900">
            <%= image_tag 'landscapes/landscape (1)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (2)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (3)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (4)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (5)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (6)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (7)', width:450, height:300 %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-lg-6">
      <div class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-interval="900">
            <%= image_tag 'landscapes/landscape (1)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (2)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (3)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (4)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (5)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (6)', width:450, height:300 %>
          </div>
          <div class="carousel-item" data-interval="900">
            <%= image_tag 'landscapes/landscape (7)', width:450, height:300 %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</main>